config/routes.rb
Rails.application.routes.draw do
  get 'test/t1'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  get 'test/t1' => 'test#t1', :as => :t1_test

  resources :users

  resources :polls
  root 'polls#index'
  get '/polls/:id/upvotes' => 'polls#increase',:as => :increase_polls
  get '/polls/:id/downvotes' => 'polls#decrease', :as => :decrease_polls

controller :sessions do
get 'login' => :new
post 'login' => :create
delete 'logout' => :destroy
end    

end

app/models/poll.rb
class Poll < ActiveRecord::Base
	before_save :default_values
  def default_values
    self.dtime ||= Time.now
    self.upvotes ||= 1
    self.downvotes ||= 1
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authorize
 

  protected

  def authorize
unless User.find_by(id: session[:user_id])
redirect_to new_user_path, notice: "Please log in"
end
end 

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def increase
    @ti= Poll.find(params[:id])
    @ti.upvotes+=1
    @ti.save
    respond_to do |format|
    format.js
  end
  end
  def decrease
   @ti= Poll.find(params[:id])
    @ti.downvotes+=1
    @ti.save
    respond_to do |format|
    format.js
  end
  end

  def index
    @polls = Poll.order(:issue)
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @time = Time.now
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @time = Time.now
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to polls_path, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:issue, :dtime, :upvotes, :downvotes)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(name: params[:name])
if user and user.authenticate(params[:password])
session[:user_id] = user.id
redirect_to polls_path
else
redirect_to new_user_path, alert: "Invalid user/password combination"
end
end

  def destroy
  	session[:user_id] = nil
 	redirect_to new_user_path
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
	skip_before_action :authorize
  def t1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize
  layout "blank"
  # GET /users
  # GET /users.json
  def index
    @psers= User.new
    @user = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    
  end
 def create
    user = User.find_by(name: params[:name])
if user and user.authenticate(params[:password])
session[:user_id] = user.id
redirect_to polls_path
else
redirect_to new_user_path, alert: "Invalid user/password combination"
end
end
  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to polls_path, notice: 'Account successfully created!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to polls_path, notice: 'Details successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :report)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollin</title>
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">
    <script src="assets/js/modernizr.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Pollin'</a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "HOME", polls_path %></a></li>
            <li><%= link_to 'CREATE POLL', new_poll_path %></li>
            <li><%= link_to "SIGN OUT", logout_path,method: :delete %></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">PAGES <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="blog.html">BLOG</a></li>
                <li><a href="single-post.html">SINGLE POST</a></li>
                <li><a href="portfolio.html">PORTFOLIO</a></li>
                <li><a href="single-project.html">SINGLE PROJECT</a></li>
              </ul>
            </li>
              
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>



<%= yield %>

<!-- *****************************************************************************************************************
   FOOTER
   ***************************************************************************************************************** -->
   <div id="footerwrap">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <h4>About</h4>
          <div class="hline-w"></div>
          <p>Pollin' is a simple polling application that allows you to create polls, anonymously! Still under development.Major improvements on the way!</p>
        </div>
        <div class="col-lg-4">
          <h4>Social Links</h4>
          <div class="hline-w"></div>
          <p>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-tumblr"></i></a>
          </p>
        </div>
        <div class="col-lg-4">
          <h4>Developers</h4>
          <div class="hline-w"></div>
          <p>
            Shrey Bagroy, IIITD<br/>
            Ambar Pal, IIITD<br/>
            
          </p>
        </div>
      
      </div><! --/row -->
    </div><! --/container -->
   </div><! --/footerwrap -->
   
</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollin</title>
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">
    <script src="assets/js/modernizr.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Pollin'</a>
        </div>
            <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <%= text_field_tag :name, params[:name], :class => "form-control", :placeholder => "Name" %>
                    </div>
                    <div class="form-group">
                       <%= password_field_tag :password, params[:password], :class => "form-control", :placeholder => "Password" %>
                    </div>
                    <div style="padding-top:10px;">
<%= submit_tag "Login", :class => "btn btn-default" %>
</div>

                </form>

        </div><!--/.nav-collapse -->
      </div>
    </div>
<% if notice %>
<p class="notice"><%= notice %> </p>
<% end %> 
<% if alert %>
<p class="alert"><%= alert %> </p>
<% end %> 


<%= yield %>

<!-- *****************************************************************************************************************
   FOOTER
   ***************************************************************************************************************** -->
   <div id="footerwrap">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <h4>About</h4>
          <div class="hline-w"></div>
          <p>Pollin' is a simple polling application that allows you to create polls, anonymously! Still under development.Major improvements on the way!</p>
        </div>
        <div class="col-lg-4">
          <h4>Social Links</h4>
          <div class="hline-w"></div>
          <p>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-tumblr"></i></a>
          </p>
        </div>
        <div class="col-lg-4">
          <h4>Developers</h4>
          <div class="hline-w"></div>
          <p>
            Shrey Bagroy, IIITD<br/>
            Ambar Pal, IIITD<br/>
            
          </p>
        </div>
      
      </div><! --/row -->
    </div><! --/container -->
   </div><! --/footerwrap -->
   
</body>
</html>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style= "text-align:center">
  <div class="field">
<br>
    <p style="font-size:50px;padding-bottom:30px;">Topic of the Poll</p>
    <%= f.text_field :issue %><br>
  </div>
  <div class="actions">
  </div>
  <div style ="padding-top:10px;padding-right:5px;">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/polls/_poll.html.erb
<p style="padding-left:400px"><%= image_tag(Gchart.pie(:legend => ['Upvotes','Downvotes'], :data => [poll.upvotes,poll.downvotes], :size => '400x200')) %></p>
          <div style ="text-align:center;">
          <%= link_to "Upvote ", increase_polls_path(:id => poll.id), :remote => true %> 
        
         <%= link_to "Downvote", decrease_polls_path(:id => poll.id), :remote => true %>
      </div>

app/views/polls/decrease.js.erb
 $("#poll_<%=@ti.id%>").html("<%= j render(partial: 'polls/poll', locals: {poll: @ti})%>")

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/increase.js.erb
 $("#poll_<%=@ti.id%>").html("<%= j render(partial: 'polls/poll', locals: {poll: @ti})%>")

app/views/polls/index.html.erb
<h1 style = "padding-top:40px;"> </h1>
<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <div id="headerwrap">
      <div class="container">
      <div class="row">
        <div class="col-lg-7 col-lg-offset-2">
          <div style="font-align:center">
            <h1>Check out all the polls here.</h1>
            <h5>And vote on some, if you like.</h5>      
          </div>
      </div>
      </div><!-- /row -->
      </div> <!-- /container -->
  </div><!-- /headerwrap -->
    <% @polls.each do |poll| %>
      <tr>
    
      
      <div style="text-align:center;">
        <p style="padding-top:30px;font-size:60px;"><%= poll.issue %></p>
        <p style="font-size:9px;">-<%= poll.dtime %></p>
      </div>
      <div class = "jrender" id="poll_<%=poll.id%>">
        <%= render(poll) %>
      </div>
         
        <p style="float:right;"><%= link_to 'Delete', poll, method: :delete, data: { confirm: 'Are you sure?' } %> </p>
      </tr>
      <div class="container">
      <div class="row centered">
        <div class ="col-md-6">
          <div style ="border-bottom: 5px solid blue;
            margin-bottom: 25px;padding-top:50px;padding-botton:1000px;"></div>
          </div>
          <div class = "col-md-6">

            <div style ="border-bottom: 5px solid orange;
            margin-bottom: 25px;padding-top:50px;padding-botton:1000px;">
        </div>
      </div>
    </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/polls/new.html.erb
<h1>New poll</h1>
<div style ="padding-top:100px;">
<%= render 'form' %>
</div>
<p style ="float:right;padding-right:50px;"><%= link_to 'Back', polls_path %></p>
<p style="padding-bottom:100px;"></p>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue:</strong>
  <%= @poll.issue %>
</p>

<p>
  <strong>Dtime:</strong>
  <%= @poll.dtime %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @poll.upvotes %>
</p>

<p>
  <strong>Downvotes:</strong>
  <%= @poll.downvotes %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/users/_form.html.erb
<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <div id="headerwrap">
      <div class="container">
      <div class="row">
        <div class="col-lg-7 col-lg-offset-2" style="height:400px;">
          <div >
            <h1 style="font-size:70px;font-align:center">Welcome to Pollin'</h1>
            <h3 style="font-size:20px;">Create an account today to start!</h3>
                
          </div>
        </div>
      </div>
      </div><!-- /row -->
    </div>

      <div style="text-align:center;">
        <p style="padding-top:30px;font-size:60px;"></p>
        <p style="font-size:9px;"></p>
      </div>
      <div class="container">
<div class="row">
  <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>Please Sign Up <small>It's free and always will be.</small></h2>
      <hr class="colorgraph">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
                      <%= f.text_field :name, :class => "form-control input-lg", :placeholder => "Name" %>
          </div>
        </div>
      </div>
  <div class="field">
    <div class="form-group">
        <%= f.text_field :email, :class => "form-control input-lg",:placeholder => "Email" %>
      </div>
    </div>
  <div class="field">
    <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.password_field :password, :class => "form-control input-lg",:placeholder => "Password" %>
          </div>
        </div>
  </div>
  <div>
   <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
              <%= f.password_field :password_confirmation, :class => "form-control input-lg", :placeholder => "Confirm Password" %>
          </div>
        </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1 style = "padding-top:40px;"> </h1>
<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <div id="headerwrap">
      <div class="container">
      <div class="row">
        <div class="col-lg-7 col-lg-offset-2" style="height:400px;">
          <div >
            <h1 style="font-size:70px;font-align:center">Welcome to Pollin'</h1>
            <h3 style="font-size:20px;">Create an account today to start!</h3>
                
          </div>
      </div>
      </div><!-- /row -->
      </div> <!-- /container -->

    <tr>
    
      
      <div style="text-align:center;">
        <p style="padding-top:30px;font-size:60px;"></p>
        <p style="font-size:9px;"></p>
      </div>
<div class="container">

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
    <form role="form">
      <%= form_for(@pser) do |f| %>
      <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pser.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @pser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     <%= render'form' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Report:</strong>
  <%= @user.report %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>